from setuptools import setup

setup (
    name='WebApp',
    version='1.0',
    packages=['venv.Lib.site-packages.py', 'venv.Lib.site-packages.py._io', 'venv.Lib.site-packages.py._log',
              'venv.Lib.site-packages.py._code', 'venv.Lib.site-packages.py._path',
              'venv.Lib.site-packages.py._process', 'venv.Lib.site-packages.py._vendored_packages',
              'venv.Lib.site-packages.bs4', 'venv.Lib.site-packages.bs4.tests', 'venv.Lib.site-packages.bs4.builder',
              'venv.Lib.site-packages.git', 'venv.Lib.site-packages.git.refs', 'venv.Lib.site-packages.git.repo',
              'venv.Lib.site-packages.git.test', 'venv.Lib.site-packages.git.test.lib',
              'venv.Lib.site-packages.git.test.performance', 'venv.Lib.site-packages.git.index',
              'venv.Lib.site-packages.git.objects', 'venv.Lib.site-packages.git.objects.submodule',
              'venv.Lib.site-packages.gym', 'venv.Lib.site-packages.gym.envs', 'venv.Lib.site-packages.gym.envs.atari',
              'venv.Lib.site-packages.gym.envs.box2d', 'venv.Lib.site-packages.gym.envs.tests',
              'venv.Lib.site-packages.gym.envs.mujoco', 'venv.Lib.site-packages.gym.envs.robotics',
              'venv.Lib.site-packages.gym.envs.robotics.hand', 'venv.Lib.site-packages.gym.envs.robotics.fetch',
              'venv.Lib.site-packages.gym.envs.toy_text', 'venv.Lib.site-packages.gym.envs.unittest',
              'venv.Lib.site-packages.gym.envs.algorithmic', 'venv.Lib.site-packages.gym.envs.algorithmic.tests',
              'venv.Lib.site-packages.gym.envs.classic_control', 'venv.Lib.site-packages.gym.utils',
              'venv.Lib.site-packages.gym.spaces', 'venv.Lib.site-packages.gym.spaces.tests',
              'venv.Lib.site-packages.gym.wrappers', 'venv.Lib.site-packages.gym.wrappers.tests',
              'venv.Lib.site-packages.gym.wrappers.monitoring', 'venv.Lib.site-packages.gym.wrappers.monitoring.tests',
              'venv.Lib.site-packages.PIL', 'venv.Lib.site-packages.pip', 'venv.Lib.site-packages.pip._vendor',
              'venv.Lib.site-packages.pip._vendor.idna', 'venv.Lib.site-packages.pip._vendor.pep517',
              'venv.Lib.site-packages.pip._vendor.pytoml', 'venv.Lib.site-packages.pip._vendor.certifi',
              'venv.Lib.site-packages.pip._vendor.chardet', 'venv.Lib.site-packages.pip._vendor.chardet.cli',
              'venv.Lib.site-packages.pip._vendor.distlib', 'venv.Lib.site-packages.pip._vendor.distlib._backport',
              'venv.Lib.site-packages.pip._vendor.msgpack', 'venv.Lib.site-packages.pip._vendor.urllib3',
              'venv.Lib.site-packages.pip._vendor.urllib3.util', 'venv.Lib.site-packages.pip._vendor.urllib3.contrib',
              'venv.Lib.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.Lib.site-packages.pip._vendor.urllib3.packages',
              'venv.Lib.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.Lib.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip._vendor.colorama', 'venv.Lib.site-packages.pip._vendor.html5lib',
              'venv.Lib.site-packages.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip._vendor.html5lib.treebuilders', 'venv.Lib.site-packages.pip._vendor.lockfile',
              'venv.Lib.site-packages.pip._vendor.progress', 'venv.Lib.site-packages.pip._vendor.requests',
              'venv.Lib.site-packages.pip._vendor.packaging', 'venv.Lib.site-packages.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip._vendor.webencodings', 'venv.Lib.site-packages.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip._internal', 'venv.Lib.site-packages.pip._internal.cli',
              'venv.Lib.site-packages.pip._internal.req', 'venv.Lib.site-packages.pip._internal.vcs',
              'venv.Lib.site-packages.pip._internal.utils', 'venv.Lib.site-packages.pip._internal.models',
              'venv.Lib.site-packages.pip._internal.commands', 'venv.Lib.site-packages.pip._internal.operations',
              'venv.Lib.site-packages.ply', 'venv.Lib.site-packages.zmq', 'venv.Lib.site-packages.zmq.log',
              'venv.Lib.site-packages.zmq.ssh', 'venv.Lib.site-packages.zmq.auth',
              'venv.Lib.site-packages.zmq.auth.asyncio', 'venv.Lib.site-packages.zmq.green',
              'venv.Lib.site-packages.zmq.green.eventloop', 'venv.Lib.site-packages.zmq.sugar',
              'venv.Lib.site-packages.zmq.tests', 'venv.Lib.site-packages.zmq.tests.asyncio',
              'venv.Lib.site-packages.zmq.utils', 'venv.Lib.site-packages.zmq.asyncio',
              'venv.Lib.site-packages.zmq.backend', 'venv.Lib.site-packages.zmq.backend.cffi',
              'venv.Lib.site-packages.zmq.backend.cython', 'venv.Lib.site-packages.zmq.devices',
              'venv.Lib.site-packages.zmq.eventloop', 'venv.Lib.site-packages.zmq.eventloop.minitornado',
              'venv.Lib.site-packages.zmq.eventloop.minitornado.platform', 'venv.Lib.site-packages.attr',
              'venv.Lib.site-packages.cffi', 'venv.Lib.site-packages.data', 'venv.Lib.site-packages.docs',
              'venv.Lib.site-packages.geos', 'venv.Lib.site-packages.geos.scripts', 'venv.Lib.site-packages.h5py',
              'venv.Lib.site-packages.h5py._hl', 'venv.Lib.site-packages.h5py.tests',
              'venv.Lib.site-packages.h5py.tests.hl', 'venv.Lib.site-packages.h5py.tests.old',
              'venv.Lib.site-packages.idna', 'venv.Lib.site-packages.jedi', 'venv.Lib.site-packages.jedi.api',
              'venv.Lib.site-packages.jedi.common', 'venv.Lib.site-packages.jedi.evaluate',
              'venv.Lib.site-packages.jedi.evaluate.context', 'venv.Lib.site-packages.jedi.evaluate.compiled',
              'venv.Lib.site-packages.lxml.lxml', 'venv.Lib.site-packages.lxml.lxml.html',
              'venv.Lib.site-packages.lxml.lxml.includes', 'venv.Lib.site-packages.lxml.lxml.isoschematron',
              'venv.Lib.site-packages.nltk', 'venv.Lib.site-packages.nltk.app', 'venv.Lib.site-packages.nltk.ccg',
              'venv.Lib.site-packages.nltk.sem', 'venv.Lib.site-packages.nltk.tag', 'venv.Lib.site-packages.nltk.tbl',
              'venv.Lib.site-packages.nltk.chat', 'venv.Lib.site-packages.nltk.draw',
              'venv.Lib.site-packages.nltk.misc', 'venv.Lib.site-packages.nltk.stem',
              'venv.Lib.site-packages.nltk.test', 'venv.Lib.site-packages.nltk.test.unit',
              'venv.Lib.site-packages.nltk.test.unit.translate', 'venv.Lib.site-packages.nltk.chunk',
              'venv.Lib.site-packages.nltk.parse', 'venv.Lib.site-packages.nltk.corpus',
              'venv.Lib.site-packages.nltk.corpus.reader', 'venv.Lib.site-packages.nltk.cluster',
              'venv.Lib.site-packages.nltk.metrics', 'venv.Lib.site-packages.nltk.twitter',
              'venv.Lib.site-packages.nltk.classify', 'venv.Lib.site-packages.nltk.tokenize',
              'venv.Lib.site-packages.nltk.inference', 'venv.Lib.site-packages.nltk.sentiment',
              'venv.Lib.site-packages.nltk.translate', 'venv.Lib.site-packages.nose', 'venv.Lib.site-packages.nose.ext',
              'venv.Lib.site-packages.nose.tools', 'venv.Lib.site-packages.nose.sphinx',
              'venv.Lib.site-packages.nose.plugins', 'venv.Lib.site-packages.past', 'venv.Lib.site-packages.past.tests',
              'venv.Lib.site-packages.past.types', 'venv.Lib.site-packages.past.utils',
              'venv.Lib.site-packages.past.builtins', 'venv.Lib.site-packages.past.translation',
              'venv.Lib.site-packages.pytz', 'venv.Lib.site-packages.shub', 'venv.Lib.site-packages.shub.image',
              'venv.Lib.site-packages.test.test_api', 'venv.Lib.site-packages.test.test_api.simple_import',
              'venv.Lib.site-packages.test.test_api.import_tree_for_usages', 'venv.Lib.site-packages.test.completion',
              'venv.Lib.site-packages.test.completion.import_tree',
              'venv.Lib.site-packages.test.completion.import_tree.pkg', 'venv.Lib.site-packages.test.test_evaluate',
              'venv.Lib.site-packages.test.test_evaluate.sample_venvs.venv27.lib.python2.7.site-packages.dir-from-foo-pth',
              'venv.Lib.site-packages.test.test_evaluate.sample_venvs.venv34.lib.python3.4.site-packages.dir-from-foo-pth',
              'venv.Lib.site-packages.test.test_evaluate.not_in_sys_path',
              'venv.Lib.site-packages.test.test_evaluate.not_in_sys_path.pkg',
              'venv.Lib.site-packages.test.test_evaluate.not_in_sys_path.not_in_sys_path_package',
              'venv.Lib.site-packages.test.test_evaluate.namespace_package.ns1.pkg',
              'venv.Lib.site-packages.test.test_evaluate.namespace_package.ns1.pkg.ns1_folder',
              'venv.Lib.site-packages.test.test_evaluate.namespace_package.ns2.pkg.ns2_folder',
              'venv.Lib.site-packages.test.test_evaluate.namespace_package.ns2.pkg.ns2_folder.nested',
              'venv.Lib.site-packages.test.test_evaluate.nested_namespaces',
              'venv.Lib.site-packages.test.test_evaluate.nested_namespaces.namespace',
              'venv.Lib.site-packages.test.test_evaluate.nested_namespaces.namespace.pkg',
              'venv.Lib.site-packages.test.test_evaluate.flask-site-packages.flask',
              'venv.Lib.site-packages.test.test_evaluate.flask-site-packages.flask.ext',
              'venv.Lib.site-packages.test.test_evaluate.flask-site-packages.flaskext',
              'venv.Lib.site-packages.test.test_evaluate.flask-site-packages.flaskext.moo',
              'venv.Lib.site-packages.test.test_evaluate.flask-site-packages.flask_baz', 'venv.Lib.site-packages.tqdm',
              'venv.Lib.site-packages.tqdm.auto', 'venv.Lib.site-packages.tqdm.autonotebook',
              'venv.Lib.site-packages.yaml', 'venv.Lib.site-packages.zope.interface',
              'venv.Lib.site-packages.zope.interface.tests', 'venv.Lib.site-packages.zope.interface.common',
              'venv.Lib.site-packages.zope.interface.common.tests', 'venv.Lib.site-packages.babel',
              'venv.Lib.site-packages.babel.messages', 'venv.Lib.site-packages.babel.localtime',
              'venv.Lib.site-packages.click', 'venv.Lib.site-packages.flask', 'venv.Lib.site-packages.flask.json',
              'venv.Lib.site-packages.gitdb', 'venv.Lib.site-packages.gitdb.db', 'venv.Lib.site-packages.gitdb.test',
              'venv.Lib.site-packages.gitdb.utils', 'venv.Lib.site-packages.isapi', 'venv.Lib.site-packages.keras',
              'venv.Lib.site-packages.keras.utils', 'venv.Lib.site-packages.keras.engine',
              'venv.Lib.site-packages.keras.layers', 'venv.Lib.site-packages.keras.legacy',
              'venv.Lib.site-packages.keras.backend', 'venv.Lib.site-packages.keras.datasets',
              'venv.Lib.site-packages.keras.wrappers', 'venv.Lib.site-packages.keras.applications',
              'venv.Lib.site-packages.keras.preprocessing', 'venv.Lib.site-packages.latex',
              'venv.Lib.site-packages.numpy', 'venv.Lib.site-packages.numpy.ma',
              'venv.Lib.site-packages.numpy.ma.tests', 'venv.Lib.site-packages.numpy.doc',
              'venv.Lib.site-packages.numpy.fft', 'venv.Lib.site-packages.numpy.fft.tests',
              'venv.Lib.site-packages.numpy.lib', 'venv.Lib.site-packages.numpy.lib.tests',
              'venv.Lib.site-packages.numpy.core', 'venv.Lib.site-packages.numpy.core.tests',
              'venv.Lib.site-packages.numpy.f2py', 'venv.Lib.site-packages.numpy.f2py.tests',
              'venv.Lib.site-packages.numpy.tests', 'venv.Lib.site-packages.numpy.compat',
              'venv.Lib.site-packages.numpy.compat.tests', 'venv.Lib.site-packages.numpy.linalg',
              'venv.Lib.site-packages.numpy.linalg.tests', 'venv.Lib.site-packages.numpy.random',
              'venv.Lib.site-packages.numpy.random.tests', 'venv.Lib.site-packages.numpy.testing',
              'venv.Lib.site-packages.numpy.testing.tests', 'venv.Lib.site-packages.numpy.testing._private',
              'venv.Lib.site-packages.numpy.distutils', 'venv.Lib.site-packages.numpy.distutils.tests',
              'venv.Lib.site-packages.numpy.distutils.command', 'venv.Lib.site-packages.numpy.distutils.fcompiler',
              'venv.Lib.site-packages.numpy.matrixlib', 'venv.Lib.site-packages.numpy.matrixlib.tests',
              'venv.Lib.site-packages.numpy.polynomial', 'venv.Lib.site-packages.numpy.polynomial.tests',
              'venv.Lib.site-packages.panda', 'venv.Lib.site-packages.parso', 'venv.Lib.site-packages.parso.pgen2',
              'venv.Lib.site-packages.parso.python', 'venv.Lib.site-packages.patsy',
              'venv.Lib.site-packages.scipy.scipy', 'venv.Lib.site-packages.scipy.scipy.io',
              'venv.Lib.site-packages.scipy.scipy.io.arff', 'venv.Lib.site-packages.scipy.scipy.io.arff.tests',
              'venv.Lib.site-packages.scipy.scipy.io.tests', 'venv.Lib.site-packages.scipy.scipy.io.matlab',
              'venv.Lib.site-packages.scipy.scipy.io.matlab.tests',
              'venv.Lib.site-packages.scipy.scipy.io.harwell_boeing',
              'venv.Lib.site-packages.scipy.scipy.io.harwell_boeing.tests', 'venv.Lib.site-packages.scipy.scipy.odr',
              'venv.Lib.site-packages.scipy.scipy.odr.tests', 'venv.Lib.site-packages.scipy.scipy._lib',
              'venv.Lib.site-packages.scipy.scipy._lib.tests', 'venv.Lib.site-packages.scipy.scipy.misc',
              'venv.Lib.site-packages.scipy.scipy.misc.tests', 'venv.Lib.site-packages.scipy.scipy.stats',
              'venv.Lib.site-packages.scipy.scipy.stats.tests', 'venv.Lib.site-packages.scipy.scipy.linalg',
              'venv.Lib.site-packages.scipy.scipy.linalg.tests', 'venv.Lib.site-packages.scipy.scipy.signal',
              'venv.Lib.site-packages.scipy.scipy.signal.tests', 'venv.Lib.site-packages.scipy.scipy.signal.windows',
              'venv.Lib.site-packages.scipy.scipy.sparse', 'venv.Lib.site-packages.scipy.scipy.sparse.tests',
              'venv.Lib.site-packages.scipy.scipy.sparse.linalg',
              'venv.Lib.site-packages.scipy.scipy.sparse.linalg.eigen',
              'venv.Lib.site-packages.scipy.scipy.sparse.linalg.eigen.arpack',
              'venv.Lib.site-packages.scipy.scipy.sparse.linalg.eigen.arpack.tests',
              'venv.Lib.site-packages.scipy.scipy.sparse.linalg.eigen.lobpcg',
              'venv.Lib.site-packages.scipy.scipy.sparse.linalg.eigen.lobpcg.tests',
              'venv.Lib.site-packages.scipy.scipy.sparse.linalg.tests',
              'venv.Lib.site-packages.scipy.scipy.sparse.linalg.dsolve',
              'venv.Lib.site-packages.scipy.scipy.sparse.linalg.dsolve.tests',
              'venv.Lib.site-packages.scipy.scipy.sparse.linalg.isolve',
              'venv.Lib.site-packages.scipy.scipy.sparse.linalg.isolve.tests',
              'venv.Lib.site-packages.scipy.scipy.sparse.csgraph',
              'venv.Lib.site-packages.scipy.scipy.sparse.csgraph.tests', 'venv.Lib.site-packages.scipy.scipy.cluster',
              'venv.Lib.site-packages.scipy.scipy.cluster.tests', 'venv.Lib.site-packages.scipy.scipy.fftpack',
              'venv.Lib.site-packages.scipy.scipy.fftpack.tests', 'venv.Lib.site-packages.scipy.scipy.ndimage',
              'venv.Lib.site-packages.scipy.scipy.ndimage.tests', 'venv.Lib.site-packages.scipy.scipy.spatial',
              'venv.Lib.site-packages.scipy.scipy.spatial.tests',
              'venv.Lib.site-packages.scipy.scipy.spatial.transform',
              'venv.Lib.site-packages.scipy.scipy.spatial.transform.tests',
              'venv.Lib.site-packages.scipy.scipy.special', 'venv.Lib.site-packages.scipy.scipy.special.tests',
              'venv.Lib.site-packages.scipy.scipy.special._precompute', 'venv.Lib.site-packages.scipy.scipy.optimize',
              'venv.Lib.site-packages.scipy.scipy.optimize._lsq', 'venv.Lib.site-packages.scipy.scipy.optimize.tests',
              'venv.Lib.site-packages.scipy.scipy.optimize._trlib',
              'venv.Lib.site-packages.scipy.scipy.optimize._shgo_lib',
              'venv.Lib.site-packages.scipy.scipy.optimize._trustregion_constr',
              'venv.Lib.site-packages.scipy.scipy.optimize._trustregion_constr.tests',
              'venv.Lib.site-packages.scipy.scipy.constants', 'venv.Lib.site-packages.scipy.scipy.constants.tests',
              'venv.Lib.site-packages.scipy.scipy.integrate', 'venv.Lib.site-packages.scipy.scipy.integrate._ivp',
              'venv.Lib.site-packages.scipy.scipy.integrate.tests', 'venv.Lib.site-packages.scipy.scipy.interpolate',
              'venv.Lib.site-packages.scipy.scipy.interpolate.tests', 'venv.Lib.site-packages.scipy.scipy._build_utils',
              'venv.Lib.site-packages.smmap', 'venv.Lib.site-packages.smmap.test', 'venv.Lib.site-packages.w3lib',
              'venv.Lib.site-packages.bleach', 'venv.Lib.site-packages.docker', 'venv.Lib.site-packages.docker.api',
              'venv.Lib.site-packages.docker.auth', 'venv.Lib.site-packages.docker.types',
              'venv.Lib.site-packages.docker.utils', 'venv.Lib.site-packages.docker.utils.ports',
              'venv.Lib.site-packages.docker.transport', 'venv.Lib.site-packages.docker.ssladapter',
              'venv.Lib.site-packages.freeze', 'venv.Lib.site-packages.future', 'venv.Lib.site-packages.future.moves',
              'venv.Lib.site-packages.future.moves.dbm', 'venv.Lib.site-packages.future.moves.html',
              'venv.Lib.site-packages.future.moves.http', 'venv.Lib.site-packages.future.moves.test',
              'venv.Lib.site-packages.future.moves.urllib', 'venv.Lib.site-packages.future.moves.xmlrpc',
              'venv.Lib.site-packages.future.moves.tkinter', 'venv.Lib.site-packages.future.tests',
              'venv.Lib.site-packages.future.types', 'venv.Lib.site-packages.future.utils',
              'venv.Lib.site-packages.future.builtins', 'venv.Lib.site-packages.future.backports',
              'venv.Lib.site-packages.future.backports.html', 'venv.Lib.site-packages.future.backports.http',
              'venv.Lib.site-packages.future.backports.test', 'venv.Lib.site-packages.future.backports.email',
              'venv.Lib.site-packages.future.backports.email.mime', 'venv.Lib.site-packages.future.backports.urllib',
              'venv.Lib.site-packages.future.backports.xmlrpc', 'venv.Lib.site-packages.future.standard_library',
              'venv.Lib.site-packages.google.protobuf', 'venv.Lib.site-packages.google.protobuf.pyext',
              'venv.Lib.site-packages.google.protobuf.internal',
              'venv.Lib.site-packages.google.protobuf.internal.import_test_package', 'venv.Lib.site-packages.jinja2',
              'venv.Lib.site-packages.pandas', 'venv.Lib.site-packages.pandas.io',
              'venv.Lib.site-packages.pandas.io.sas', 'venv.Lib.site-packages.pandas.io.json',
              'venv.Lib.site-packages.pandas.io.formats', 'venv.Lib.site-packages.pandas.io.msgpack',
              'venv.Lib.site-packages.pandas.io.clipboard', 'venv.Lib.site-packages.pandas.api',
              'venv.Lib.site-packages.pandas.api.types', 'venv.Lib.site-packages.pandas.api.extensions',
              'venv.Lib.site-packages.pandas.core', 'venv.Lib.site-packages.pandas.core.util',
              'venv.Lib.site-packages.pandas.core.tools', 'venv.Lib.site-packages.pandas.core.arrays',
              'venv.Lib.site-packages.pandas.core.dtypes', 'venv.Lib.site-packages.pandas.core.sparse',
              'venv.Lib.site-packages.pandas.core.groupby', 'venv.Lib.site-packages.pandas.core.indexes',
              'venv.Lib.site-packages.pandas.core.reshape', 'venv.Lib.site-packages.pandas.core.internals',
              'venv.Lib.site-packages.pandas.core.computation', 'venv.Lib.site-packages.pandas.util',
              'venv.Lib.site-packages.pandas._libs', 'venv.Lib.site-packages.pandas._libs.tslibs',
              'venv.Lib.site-packages.pandas.tests', 'venv.Lib.site-packages.pandas.tests.io',
              'venv.Lib.site-packages.pandas.tests.io.sas', 'venv.Lib.site-packages.pandas.tests.io.json',
              'venv.Lib.site-packages.pandas.tests.io.parser', 'venv.Lib.site-packages.pandas.tests.io.formats',
              'venv.Lib.site-packages.pandas.tests.io.msgpack', 'venv.Lib.site-packages.pandas.tests.api',
              'venv.Lib.site-packages.pandas.tests.util', 'venv.Lib.site-packages.pandas.tests.frame',
              'venv.Lib.site-packages.pandas.tests.tools', 'venv.Lib.site-packages.pandas.tests.arrays',
              'venv.Lib.site-packages.pandas.tests.arrays.sparse',
              'venv.Lib.site-packages.pandas.tests.arrays.interval',
              'venv.Lib.site-packages.pandas.tests.arrays.categorical', 'venv.Lib.site-packages.pandas.tests.dtypes',
              'venv.Lib.site-packages.pandas.tests.dtypes.cast', 'venv.Lib.site-packages.pandas.tests.scalar',
              'venv.Lib.site-packages.pandas.tests.scalar.period',
              'venv.Lib.site-packages.pandas.tests.scalar.interval',
              'venv.Lib.site-packages.pandas.tests.scalar.timedelta',
              'venv.Lib.site-packages.pandas.tests.scalar.timestamp', 'venv.Lib.site-packages.pandas.tests.series',
              'venv.Lib.site-packages.pandas.tests.series.indexing', 'venv.Lib.site-packages.pandas.tests.sparse',
              'venv.Lib.site-packages.pandas.tests.sparse.frame', 'venv.Lib.site-packages.pandas.tests.sparse.series',
              'venv.Lib.site-packages.pandas.tests.tslibs', 'venv.Lib.site-packages.pandas.tests.generic',
              'venv.Lib.site-packages.pandas.tests.groupby', 'venv.Lib.site-packages.pandas.tests.groupby.aggregate',
              'venv.Lib.site-packages.pandas.tests.indexes', 'venv.Lib.site-packages.pandas.tests.indexes.multi',
              'venv.Lib.site-packages.pandas.tests.indexes.period',
              'venv.Lib.site-packages.pandas.tests.indexes.interval',
              'venv.Lib.site-packages.pandas.tests.indexes.datetimes',
              'venv.Lib.site-packages.pandas.tests.indexes.timedeltas', 'venv.Lib.site-packages.pandas.tests.reshape',
              'venv.Lib.site-packages.pandas.tests.reshape.merge', 'venv.Lib.site-packages.pandas.tests.tseries',
              'venv.Lib.site-packages.pandas.tests.tseries.offsets', 'venv.Lib.site-packages.pandas.tests.indexing',
              'venv.Lib.site-packages.pandas.tests.indexing.interval',
              'venv.Lib.site-packages.pandas.tests.indexing.multiindex', 'venv.Lib.site-packages.pandas.tests.plotting',
              'venv.Lib.site-packages.pandas.tests.resample', 'venv.Lib.site-packages.pandas.tests.extension',
              'venv.Lib.site-packages.pandas.tests.extension.base',
              'venv.Lib.site-packages.pandas.tests.extension.json',
              'venv.Lib.site-packages.pandas.tests.extension.arrow',
              'venv.Lib.site-packages.pandas.tests.extension.numpy_',
              'venv.Lib.site-packages.pandas.tests.extension.decimal', 'venv.Lib.site-packages.pandas.tests.internals',
              'venv.Lib.site-packages.pandas.tests.arithmetic', 'venv.Lib.site-packages.pandas.tests.reductions',
              'venv.Lib.site-packages.pandas.tests.computation', 'venv.Lib.site-packages.pandas.arrays',
              'venv.Lib.site-packages.pandas.compat', 'venv.Lib.site-packages.pandas.compat.numpy',
              'venv.Lib.site-packages.pandas.errors', 'venv.Lib.site-packages.pandas.tseries',
              'venv.Lib.site-packages.pandas.plotting', 'venv.Lib.site-packages.pandoc',
              'venv.Lib.site-packages.pandoc.doctest', 'venv.Lib.site-packages.pluggy', 'venv.Lib.site-packages.psutil',
              'venv.Lib.site-packages.psutil.tests', 'venv.Lib.site-packages.pyasn1',
              'venv.Lib.site-packages.pyasn1.type', 'venv.Lib.site-packages.pyasn1.codec',
              'venv.Lib.site-packages.pyasn1.codec.ber', 'venv.Lib.site-packages.pyasn1.codec.cer',
              'venv.Lib.site-packages.pyasn1.codec.der', 'venv.Lib.site-packages.pyasn1.codec.native',
              'venv.Lib.site-packages.pyasn1.compat', 'venv.Lib.site-packages.pyglet',
              'venv.Lib.site-packages.pyglet.gl', 'venv.Lib.site-packages.pyglet.app',
              'venv.Lib.site-packages.pyglet.font', 'venv.Lib.site-packages.pyglet.libs',
              'venv.Lib.site-packages.pyglet.libs.x11', 'venv.Lib.site-packages.pyglet.libs.win32',
              'venv.Lib.site-packages.pyglet.libs.darwin', 'venv.Lib.site-packages.pyglet.libs.darwin.cocoapy',
              'venv.Lib.site-packages.pyglet.text', 'venv.Lib.site-packages.pyglet.text.formats',
              'venv.Lib.site-packages.pyglet.image', 'venv.Lib.site-packages.pyglet.image.codecs',
              'venv.Lib.site-packages.pyglet.input', 'venv.Lib.site-packages.pyglet.media',
              'venv.Lib.site-packages.pyglet.media.drivers', 'venv.Lib.site-packages.pyglet.media.drivers.pulse',
              'venv.Lib.site-packages.pyglet.media.drivers.openal',
              'venv.Lib.site-packages.pyglet.media.drivers.directsound', 'venv.Lib.site-packages.pyglet.media.sources',
              'venv.Lib.site-packages.pyglet.canvas', 'venv.Lib.site-packages.pyglet.window',
              'venv.Lib.site-packages.pyglet.window.xlib', 'venv.Lib.site-packages.pyglet.window.cocoa',
              'venv.Lib.site-packages.pyglet.window.win32', 'venv.Lib.site-packages.pyglet.window.carbon',
              'venv.Lib.site-packages.pyglet.extlibs', 'venv.Lib.site-packages.pyglet.graphics',
              'venv.Lib.site-packages.pylama', 'venv.Lib.site-packages.pylama.libs',
              'venv.Lib.site-packages.pylama.lint', 'venv.Lib.site-packages.sphinx',
              'venv.Lib.site-packages.sphinx.cmd', 'venv.Lib.site-packages.sphinx.ext',
              'venv.Lib.site-packages.sphinx.ext.autodoc', 'venv.Lib.site-packages.sphinx.ext.napoleon',
              'venv.Lib.site-packages.sphinx.ext.autosummary', 'venv.Lib.site-packages.sphinx.util',
              'venv.Lib.site-packages.sphinx.util.stemmer', 'venv.Lib.site-packages.sphinx.locale',
              'venv.Lib.site-packages.sphinx.pycode', 'venv.Lib.site-packages.sphinx.search',
              'venv.Lib.site-packages.sphinx.domains', 'venv.Lib.site-packages.sphinx.testing',
              'venv.Lib.site-packages.sphinx.writers', 'venv.Lib.site-packages.sphinx.builders',
              'venv.Lib.site-packages.sphinx.directives', 'venv.Lib.site-packages.sphinx.transforms',
              'venv.Lib.site-packages.sphinx.transforms.post_transforms', 'venv.Lib.site-packages.sphinx.websupport',
              'venv.Lib.site-packages.sphinx.websupport.search', 'venv.Lib.site-packages.sphinx.websupport.storage',
              'venv.Lib.site-packages.sphinx.environment', 'venv.Lib.site-packages.sphinx.environment.adapters',
              'venv.Lib.site-packages.sphinx.environment.collectors', 'venv.Lib.site-packages.tweepy',
              'venv.Lib.site-packages.winpty', 'venv.Lib.site-packages.winpty.tests',
              'venv.Lib.site-packages.winpty._winpty', 'venv.Lib.site-packages._pytest',
              'venv.Lib.site-packages._pytest._code', 'venv.Lib.site-packages._pytest.assertion',
              'venv.Lib.site-packages.automat', 'venv.Lib.site-packages.automat._test',
              'venv.Lib.site-packages.certifi', 'venv.Lib.site-packages.chardet', 'venv.Lib.site-packages.chardet.cli',
              'venv.Lib.site-packages.IPython', 'venv.Lib.site-packages.IPython.lib',
              'venv.Lib.site-packages.IPython.lib.tests', 'venv.Lib.site-packages.IPython.core',
              'venv.Lib.site-packages.IPython.core.tests', 'venv.Lib.site-packages.IPython.core.magics',
              'venv.Lib.site-packages.IPython.utils', 'venv.Lib.site-packages.IPython.utils.tests',
              'venv.Lib.site-packages.IPython.kernel', 'venv.Lib.site-packages.IPython.testing',
              'venv.Lib.site-packages.IPython.testing.tests', 'venv.Lib.site-packages.IPython.testing.plugin',
              'venv.Lib.site-packages.IPython.external', 'venv.Lib.site-packages.IPython.external.decorators',
              'venv.Lib.site-packages.IPython.terminal', 'venv.Lib.site-packages.IPython.terminal.tests',
              'venv.Lib.site-packages.IPython.terminal.pt_inputhooks', 'venv.Lib.site-packages.IPython.sphinxext',
              'venv.Lib.site-packages.IPython.extensions', 'venv.Lib.site-packages.IPython.extensions.tests',
              'venv.Lib.site-packages.luminol', 'venv.Lib.site-packages.luminol.modules',
              'venv.Lib.site-packages.luminol.algorithms',
              'venv.Lib.site-packages.luminol.algorithms.correlator_algorithms',
              'venv.Lib.site-packages.luminol.algorithms.anomaly_detector_algorithms', 'venv.Lib.site-packages.OpenSSL',
              'venv.Lib.site-packages.pymysql', 'venv.Lib.site-packages.pymysql.tests',
              'venv.Lib.site-packages.pymysql.tests.thirdparty',
              'venv.Lib.site-packages.pymysql.tests.thirdparty.test_MySQLdb',
              'venv.Lib.site-packages.pymysql.constants', 'venv.Lib.site-packages.seaborn',
              'venv.Lib.site-packages.seaborn.tests', 'venv.Lib.site-packages.seaborn.external',
              'venv.Lib.site-packages.tornado', 'venv.Lib.site-packages.tornado.test',
              'venv.Lib.site-packages.tornado.platform', 'venv.Lib.site-packages.twisted',
              'venv.Lib.site-packages.twisted.tap', 'venv.Lib.site-packages.twisted.web',
              'venv.Lib.site-packages.twisted.web.test', 'venv.Lib.site-packages.twisted.web._auth',
              'venv.Lib.site-packages.twisted.cred', 'venv.Lib.site-packages.twisted.cred.test',
              'venv.Lib.site-packages.twisted.mail', 'venv.Lib.site-packages.twisted.mail.test',
              'venv.Lib.site-packages.twisted.pair', 'venv.Lib.site-packages.twisted.pair.test',
              'venv.Lib.site-packages.twisted.test', 'venv.Lib.site-packages.twisted.conch',
              'venv.Lib.site-packages.twisted.conch.ui', 'venv.Lib.site-packages.twisted.conch.ssh',
              'venv.Lib.site-packages.twisted.conch.test', 'venv.Lib.site-packages.twisted.conch.client',
              'venv.Lib.site-packages.twisted.conch.insults', 'venv.Lib.site-packages.twisted.conch.scripts',
              'venv.Lib.site-packages.twisted.conch.openssh_compat', 'venv.Lib.site-packages.twisted.names',
              'venv.Lib.site-packages.twisted.names.test', 'venv.Lib.site-packages.twisted.trial',
              'venv.Lib.site-packages.twisted.trial.test', 'venv.Lib.site-packages.twisted.trial._dist',
              'venv.Lib.site-packages.twisted.trial._dist.test', 'venv.Lib.site-packages.twisted.words',
              'venv.Lib.site-packages.twisted.words.im', 'venv.Lib.site-packages.twisted.words.test',
              'venv.Lib.site-packages.twisted.words.xish', 'venv.Lib.site-packages.twisted.words.protocols',
              'venv.Lib.site-packages.twisted.words.protocols.jabber', 'venv.Lib.site-packages.twisted.logger',
              'venv.Lib.site-packages.twisted.logger.test', 'venv.Lib.site-packages.twisted.python',
              'venv.Lib.site-packages.twisted.python.test', 'venv.Lib.site-packages.twisted.runner',
              'venv.Lib.site-packages.twisted.runner.test', 'venv.Lib.site-packages.twisted.spread',
              'venv.Lib.site-packages.twisted.spread.test', 'venv.Lib.site-packages.twisted.plugins',
              'venv.Lib.site-packages.twisted.scripts', 'venv.Lib.site-packages.twisted.scripts.test',
              'venv.Lib.site-packages.twisted._threads', 'venv.Lib.site-packages.twisted._threads.test',
              'venv.Lib.site-packages.twisted.internet', 'venv.Lib.site-packages.twisted.internet.test',
              'venv.Lib.site-packages.twisted.internet.iocpreactor', 'venv.Lib.site-packages.twisted.persisted',
              'venv.Lib.site-packages.twisted.persisted.test', 'venv.Lib.site-packages.twisted.protocols',
              'venv.Lib.site-packages.twisted.protocols.test', 'venv.Lib.site-packages.twisted.protocols.haproxy',
              'venv.Lib.site-packages.twisted.protocols.haproxy.test', 'venv.Lib.site-packages.twisted.enterprise',
              'venv.Lib.site-packages.twisted.application', 'venv.Lib.site-packages.twisted.application.test',
              'venv.Lib.site-packages.twisted.application.twist',
              'venv.Lib.site-packages.twisted.application.twist.test',
              'venv.Lib.site-packages.twisted.application.runner',
              'venv.Lib.site-packages.twisted.application.runner.test', 'venv.Lib.site-packages.twisted.positioning',
              'venv.Lib.site-packages.twisted.positioning.test', 'venv.Lib.site-packages.urllib3',
              'venv.Lib.site-packages.urllib3.util', 'venv.Lib.site-packages.urllib3.contrib',
              'venv.Lib.site-packages.urllib3.contrib._securetransport', 'venv.Lib.site-packages.urllib3.packages',
              'venv.Lib.site-packages.urllib3.packages.backports',
              'venv.Lib.site-packages.urllib3.packages.ssl_match_hostname', 'venv.Lib.site-packages.visitor',
              'venv.Lib.site-packages.wcwidth', 'venv.Lib.site-packages.wcwidth.tests',
              'venv.Lib.site-packages.adodbapi', 'venv.Lib.site-packages.backcall', 'venv.Lib.site-packages.colorama',
              'venv.Lib.site-packages.coverage', 'venv.Lib.site-packages.DateTime',
              'venv.Lib.site-packages.DateTime.tests', 'venv.Lib.site-packages.dateutil',
              'venv.Lib.site-packages.dateutil.tz', 'venv.Lib.site-packages.dateutil.parser',
              'venv.Lib.site-packages.dateutil.zoneinfo', 'venv.Lib.site-packages.docutils',
              'venv.Lib.site-packages.docutils.utils', 'venv.Lib.site-packages.docutils.utils.math',
              'venv.Lib.site-packages.docutils.parsers', 'venv.Lib.site-packages.docutils.parsers.rst',
              'venv.Lib.site-packages.docutils.parsers.rst.languages',
              'venv.Lib.site-packages.docutils.parsers.rst.directives', 'venv.Lib.site-packages.docutils.readers',
              'venv.Lib.site-packages.docutils.writers', 'venv.Lib.site-packages.docutils.writers.xetex',
              'venv.Lib.site-packages.docutils.writers.latex2e', 'venv.Lib.site-packages.docutils.writers.odf_odt',
              'venv.Lib.site-packages.docutils.writers.s5_html', 'venv.Lib.site-packages.docutils.writers.pep_html',
              'venv.Lib.site-packages.docutils.writers.html4css1',
              'venv.Lib.site-packages.docutils.writers.html5_polyglot', 'venv.Lib.site-packages.docutils.languages',
              'venv.Lib.site-packages.docutils.transforms', 'venv.Lib.site-packages.dominate',
              'venv.Lib.site-packages.examples', 'venv.Lib.site-packages.funcsigs', 'venv.Lib.site-packages.gunicorn',
              'venv.Lib.site-packages.gunicorn.app', 'venv.Lib.site-packages.gunicorn.http',
              'venv.Lib.site-packages.gunicorn.workers', 'venv.Lib.site-packages.gunicorn.instrument',
              'venv.Lib.site-packages.hamcrest', 'venv.Lib.site-packages.hamcrest.core',
              'venv.Lib.site-packages.hamcrest.core.core', 'venv.Lib.site-packages.hamcrest.core.helpers',
              'venv.Lib.site-packages.hamcrest.library', 'venv.Lib.site-packages.hamcrest.library.text',
              'venv.Lib.site-packages.hamcrest.library.number', 'venv.Lib.site-packages.hamcrest.library.object',
              'venv.Lib.site-packages.hamcrest.library.collection',
              'venv.Lib.site-packages.hamcrest.library.integration', 'venv.Lib.site-packages.html5lib',
              'venv.Lib.site-packages.html5lib._trie', 'venv.Lib.site-packages.html5lib.filters',
              'venv.Lib.site-packages.html5lib.treewalkers', 'venv.Lib.site-packages.html5lib.treeadapters',
              'venv.Lib.site-packages.html5lib.treebuilders', 'venv.Lib.site-packages.nbformat',
              'venv.Lib.site-packages.nbformat.v1', 'venv.Lib.site-packages.nbformat.v1.tests',
              'venv.Lib.site-packages.nbformat.v2', 'venv.Lib.site-packages.nbformat.v2.tests',
              'venv.Lib.site-packages.nbformat.v3', 'venv.Lib.site-packages.nbformat.v3.tests',
              'venv.Lib.site-packages.nbformat.v4', 'venv.Lib.site-packages.nbformat.v4.tests',
              'venv.Lib.site-packages.nbformat.tests', 'venv.Lib.site-packages.notebook',
              'venv.Lib.site-packages.notebook.auth', 'venv.Lib.site-packages.notebook.auth.tests',
              'venv.Lib.site-packages.notebook.base', 'venv.Lib.site-packages.notebook.edit',
              'venv.Lib.site-packages.notebook.i18n', 'venv.Lib.site-packages.notebook.tree',
              'venv.Lib.site-packages.notebook.tree.tests', 'venv.Lib.site-packages.notebook.view',
              'venv.Lib.site-packages.notebook.files', 'venv.Lib.site-packages.notebook.tests',
              'venv.Lib.site-packages.notebook.bundler', 'venv.Lib.site-packages.notebook.bundler.tests',
              'venv.Lib.site-packages.notebook.notebook', 'venv.Lib.site-packages.notebook.services',
              'venv.Lib.site-packages.notebook.services.api', 'venv.Lib.site-packages.notebook.services.api.tests',
              'venv.Lib.site-packages.notebook.services.config',
              'venv.Lib.site-packages.notebook.services.config.tests',
              'venv.Lib.site-packages.notebook.services.kernels',
              'venv.Lib.site-packages.notebook.services.kernels.tests',
              'venv.Lib.site-packages.notebook.services.contents',
              'venv.Lib.site-packages.notebook.services.contents.tests',
              'venv.Lib.site-packages.notebook.services.security', 'venv.Lib.site-packages.notebook.services.sessions',
              'venv.Lib.site-packages.notebook.services.sessions.tests',
              'venv.Lib.site-packages.notebook.services.nbconvert',
              'venv.Lib.site-packages.notebook.services.nbconvert.tests',
              'venv.Lib.site-packages.notebook.services.kernelspecs',
              'venv.Lib.site-packages.notebook.services.kernelspecs.tests', 'venv.Lib.site-packages.notebook.terminal',
              'venv.Lib.site-packages.notebook.nbconvert', 'venv.Lib.site-packages.notebook.nbconvert.tests',
              'venv.Lib.site-packages.notebook.kernelspecs', 'venv.Lib.site-packages.oauthlib',
              'venv.Lib.site-packages.oauthlib.oauth1', 'venv.Lib.site-packages.oauthlib.oauth1.rfc5849',
              'venv.Lib.site-packages.oauthlib.oauth1.rfc5849.endpoints', 'venv.Lib.site-packages.oauthlib.oauth2',
              'venv.Lib.site-packages.oauthlib.oauth2.rfc6749',
              'venv.Lib.site-packages.oauthlib.oauth2.rfc6749.clients',
              'venv.Lib.site-packages.oauthlib.oauth2.rfc6749.endpoints',
              'venv.Lib.site-packages.oauthlib.oauth2.rfc6749.grant_types', 'venv.Lib.site-packages.pyflakes',
              'venv.Lib.site-packages.pyflakes.test', 'venv.Lib.site-packages.pyflakes.scripts',
              'venv.Lib.site-packages.pygments', 'venv.Lib.site-packages.pygments.lexers',
              'venv.Lib.site-packages.pygments.styles', 'venv.Lib.site-packages.pygments.filters',
              'venv.Lib.site-packages.pygments.formatters', 'venv.Lib.site-packages.queuelib',
              'venv.Lib.site-packages.queuelib.tests', 'venv.Lib.site-packages.requests',
              'venv.Lib.site-packages.selenium', 'venv.Lib.site-packages.selenium.common',
              'venv.Lib.site-packages.selenium.webdriver', 'venv.Lib.site-packages.selenium.webdriver.ie',
              'venv.Lib.site-packages.selenium.webdriver.edge', 'venv.Lib.site-packages.selenium.webdriver.opera',
              'venv.Lib.site-packages.selenium.webdriver.chrome', 'venv.Lib.site-packages.selenium.webdriver.common',
              'venv.Lib.site-packages.selenium.webdriver.common.html5',
              'venv.Lib.site-packages.selenium.webdriver.common.actions',
              'venv.Lib.site-packages.selenium.webdriver.remote', 'venv.Lib.site-packages.selenium.webdriver.safari',
              'venv.Lib.site-packages.selenium.webdriver.android', 'venv.Lib.site-packages.selenium.webdriver.firefox',
              'venv.Lib.site-packages.selenium.webdriver.support',
              'venv.Lib.site-packages.selenium.webdriver.phantomjs',
              'venv.Lib.site-packages.selenium.webdriver.webkitgtk',
              'venv.Lib.site-packages.selenium.webdriver.blackberry', 'venv.Lib.site-packages.testpath',
              'venv.Lib.site-packages.werkzeug', 'venv.Lib.site-packages.werkzeug.debug',
              'venv.Lib.site-packages.werkzeug.contrib', 'venv.Lib.site-packages.win32com',
              'venv.Lib.site-packages.win32com.test', 'venv.Lib.site-packages.win32com.demos',
              'venv.Lib.site-packages.win32com.client', 'venv.Lib.site-packages.win32com.makegw',
              'venv.Lib.site-packages.win32com.server', 'venv.Lib.site-packages.win32com.servers',
              'venv.Lib.site-packages.alabaster', 'venv.Lib.site-packages.cssselect',
              'venv.Lib.site-packages.dataframe', 'venv.Lib.site-packages.dataframe.search_tree',
              'venv.Lib.site-packages.hyperlink', 'venv.Lib.site-packages.hyperlink.test',
              'venv.Lib.site-packages.ipykernel', 'venv.Lib.site-packages.ipykernel.gui',
              'venv.Lib.site-packages.ipykernel.comm', 'venv.Lib.site-packages.ipykernel.pylab',
              'venv.Lib.site-packages.ipykernel.tests', 'venv.Lib.site-packages.ipykernel.inprocess',
              'venv.Lib.site-packages.ipykernel.inprocess.tests', 'venv.Lib.site-packages.nbconvert',
              'venv.Lib.site-packages.nbconvert.tests', 'venv.Lib.site-packages.nbconvert.utils',
              'venv.Lib.site-packages.nbconvert.utils.tests', 'venv.Lib.site-packages.nbconvert.filters',
              'venv.Lib.site-packages.nbconvert.filters.tests', 'venv.Lib.site-packages.nbconvert.writers',
              'venv.Lib.site-packages.nbconvert.writers.tests', 'venv.Lib.site-packages.nbconvert.exporters',
              'venv.Lib.site-packages.nbconvert.exporters.tests', 'venv.Lib.site-packages.nbconvert.resources',
              'venv.Lib.site-packages.nbconvert.preprocessors', 'venv.Lib.site-packages.nbconvert.preprocessors.tests',
              'venv.Lib.site-packages.nbconvert.postprocessors',
              'venv.Lib.site-packages.nbconvert.postprocessors.tests', 'venv.Lib.site-packages.packaging',
              'venv.Lib.site-packages.pycparser', 'venv.Lib.site-packages.pycparser.ply',
              'venv.Lib.site-packages.pydotplus', 'venv.Lib.site-packages.pythonwin.pywin',
              'venv.Lib.site-packages.pythonwin.pywin.mfc', 'venv.Lib.site-packages.pythonwin.pywin.idle',
              'venv.Lib.site-packages.pythonwin.pywin.Demos.ocx', 'venv.Lib.site-packages.pythonwin.pywin.tools',
              'venv.Lib.site-packages.pythonwin.pywin.dialogs', 'venv.Lib.site-packages.pythonwin.pywin.docking',
              'venv.Lib.site-packages.pythonwin.pywin.debugger', 'venv.Lib.site-packages.pythonwin.pywin.framework',
              'venv.Lib.site-packages.pythonwin.pywin.framework.editor',
              'venv.Lib.site-packages.pythonwin.pywin.framework.editor.color',
              'venv.Lib.site-packages.pythonwin.pywin.scintilla', 'venv.Lib.site-packages.qtconsole',
              'venv.Lib.site-packages.qtconsole.tests', 'venv.Lib.site-packages.soupsieve',
              'venv.Lib.site-packages.terminado', 'venv.Lib.site-packages.terminado.tests',
              'venv.Lib.site-packages.traitlets', 'venv.Lib.site-packages.traitlets.tests',
              'venv.Lib.site-packages.traitlets.utils', 'venv.Lib.site-packages.traitlets.utils.tests',
              'venv.Lib.site-packages.traitlets.config', 'venv.Lib.site-packages.traitlets.config.tests',
              'venv.Lib.site-packages.websocket', 'venv.Lib.site-packages.websocket.tests',
              'venv.Lib.site-packages.asn1crypto', 'venv.Lib.site-packages.asn1crypto._perf',
              'venv.Lib.site-packages.brewer2mpl', 'venv.Lib.site-packages.brewer2mpl.wesanderson',
              'venv.Lib.site-packages.constantly', 'venv.Lib.site-packages.defusedxml',
              'venv.Lib.site-packages.ipywidgets', 'venv.Lib.site-packages.ipywidgets.tests',
              'venv.Lib.site-packages.ipywidgets.widgets', 'venv.Lib.site-packages.ipywidgets.widgets.tests',
              'venv.Lib.site-packages.jsonschema', 'venv.Lib.site-packages.jsonschema.tests',
              'venv.Lib.site-packages.jupyterlab', 'venv.Lib.site-packages.jupyterlab.tests',
              'venv.Lib.site-packages.markupsafe', 'venv.Lib.site-packages.matplotlib',
              'venv.Lib.site-packages.matplotlib.tri', 'venv.Lib.site-packages.matplotlib.axes',
              'venv.Lib.site-packages.matplotlib.cbook', 'venv.Lib.site-packages.matplotlib.style',
              'venv.Lib.site-packages.matplotlib.compat', 'venv.Lib.site-packages.matplotlib.testing',
              'venv.Lib.site-packages.matplotlib.testing._nose',
              'venv.Lib.site-packages.matplotlib.testing._nose.plugins',
              'venv.Lib.site-packages.matplotlib.testing.jpl_units', 'venv.Lib.site-packages.matplotlib.backends',
              'venv.Lib.site-packages.matplotlib.backends.qt_editor', 'venv.Lib.site-packages.matplotlib.sphinxext',
              'venv.Lib.site-packages.matplotlib.projections', 'venv.Lib.site-packages.pydispatch',
              'venv.Lib.site-packages.pydocstyle', 'venv.Lib.site-packages.pykml_geos',
              'venv.Lib.site-packages.pytest_cov', 'venv.Lib.site-packages.send2trash',
              'venv.Lib.site-packages.exampleproj', 'venv.Lib.site-packages.incremental',
              'venv.Lib.site-packages.incremental.tests', 'venv.Lib.site-packages.libfuturize',
              'venv.Lib.site-packages.libfuturize.fixes', 'venv.Lib.site-packages.scrapinghub',
              'venv.Lib.site-packages.scrapinghub.client', 'venv.Lib.site-packages.scrapinghub.hubstorage',
              'venv.Lib.site-packages.shutilwhich', 'venv.Lib.site-packages.win32comext.adsi',
              'venv.Lib.site-packages.win32comext.bits', 'venv.Lib.site-packages.win32comext.mapi',
              'venv.Lib.site-packages.win32comext.shell', 'venv.Lib.site-packages.win32comext.axdebug',
              'venv.Lib.site-packages.win32comext.ifilter', 'venv.Lib.site-packages.win32comext.propsys',
              'venv.Lib.site-packages.win32comext.axscript', 'venv.Lib.site-packages.win32comext.axscript.client',
              'venv.Lib.site-packages.win32comext.axscript.server', 'venv.Lib.site-packages.win32comext.internet',
              'venv.Lib.site-packages.win32comext.axcontrol', 'venv.Lib.site-packages.win32comext.directsound',
              'venv.Lib.site-packages.win32comext.directsound.test', 'venv.Lib.site-packages.win32comext.authorization',
              'venv.Lib.site-packages.win32comext.taskscheduler', 'venv.Lib.site-packages.atomicwrites',
              'venv.Lib.site-packages.cryptography', 'venv.Lib.site-packages.cryptography.x509',
              'venv.Lib.site-packages.cryptography.hazmat', 'venv.Lib.site-packages.cryptography.hazmat.backends',
              'venv.Lib.site-packages.cryptography.hazmat.backends.openssl',
              'venv.Lib.site-packages.cryptography.hazmat.bindings',
              'venv.Lib.site-packages.cryptography.hazmat.bindings.openssl',
              'venv.Lib.site-packages.cryptography.hazmat.primitives',
              'venv.Lib.site-packages.cryptography.hazmat.primitives.kdf',
              'venv.Lib.site-packages.cryptography.hazmat.primitives.ciphers',
              'venv.Lib.site-packages.cryptography.hazmat.primitives.twofactor',
              'venv.Lib.site-packages.cryptography.hazmat.primitives.asymmetric', 'venv.Lib.site-packages.itsdangerous',
              'venv.Lib.site-packages.jupyter_core', 'venv.Lib.site-packages.jupyter_core.tests',
              'venv.Lib.site-packages.jupyter_core.utils', 'venv.Lib.site-packages.mpl_toolkits.mplot3d',
              'venv.Lib.site-packages.mpl_toolkits.axes_grid', 'venv.Lib.site-packages.mpl_toolkits.axes_grid1',
              'venv.Lib.site-packages.mpl_toolkits.axisartist', 'venv.Lib.site-packages.webencodings',
              'venv.Lib.site-packages.dockerpycreds', 'venv.Lib.site-packages.libpasteurize',
              'venv.Lib.site-packages.libpasteurize.fixes', 'venv.Lib.site-packages.sphinxcontrib.websupport',
              'venv.Lib.site-packages.sphinxcontrib.websupport.search',
              'venv.Lib.site-packages.sphinxcontrib.websupport.storage', 'venv.Lib.site-packages.jupyter_client',
              'venv.Lib.site-packages.jupyter_client.tests', 'venv.Lib.site-packages.jupyter_client.ioloop',
              'venv.Lib.site-packages.jupyter_client.blocking', 'venv.Lib.site-packages.more_itertools',
              'venv.Lib.site-packages.more_itertools.tests', 'venv.Lib.site-packages.prompt_toolkit',
              'venv.Lib.site-packages.prompt_toolkit.input', 'venv.Lib.site-packages.prompt_toolkit.layout',
              'venv.Lib.site-packages.prompt_toolkit.lexers', 'venv.Lib.site-packages.prompt_toolkit.output',
              'venv.Lib.site-packages.prompt_toolkit.styles', 'venv.Lib.site-packages.prompt_toolkit.contrib',
              'venv.Lib.site-packages.prompt_toolkit.contrib.telnet',
              'venv.Lib.site-packages.prompt_toolkit.contrib.completers',
              'venv.Lib.site-packages.prompt_toolkit.contrib.regular_languages',
              'venv.Lib.site-packages.prompt_toolkit.filters', 'venv.Lib.site-packages.prompt_toolkit.widgets',
              'venv.Lib.site-packages.prompt_toolkit.clipboard', 'venv.Lib.site-packages.prompt_toolkit.eventloop',
              'venv.Lib.site-packages.prompt_toolkit.shortcuts',
              'venv.Lib.site-packages.prompt_toolkit.shortcuts.progress_bar',
              'venv.Lib.site-packages.prompt_toolkit.completion', 'venv.Lib.site-packages.prompt_toolkit.application',
              'venv.Lib.site-packages.prompt_toolkit.key_binding',
              'venv.Lib.site-packages.prompt_toolkit.key_binding.bindings',
              'venv.Lib.site-packages.prompt_toolkit.formatted_text', 'venv.Lib.site-packages.pyasn1_modules',
              'venv.Lib.site-packages.flask_bootstrap', 'venv.Lib.site-packages.jupyter_console',
              'venv.Lib.site-packages.jupyter_console.tests', 'venv.Lib.site-packages.snowballstemmer',
              'venv.Lib.site-packages.ipython_genutils', 'venv.Lib.site-packages.ipython_genutils.tests',
              'venv.Lib.site-packages.ipython_genutils.testing', 'venv.Lib.site-packages.service_identity',
              'venv.Lib.site-packages.jupyterlab_server', 'venv.Lib.site-packages.jupyterlab_server.tests',
              'venv.Lib.site-packages.prometheus_client', 'venv.Lib.site-packages.prometheus_client.bridge',
              'venv.Lib.site-packages.prometheus_client.twisted',
              'venv.Lib.site-packages.prometheus_client.openmetrics', 'venv.Lib.site-packages.requests_oauthlib',
              'venv.Lib.site-packages.requests_oauthlib.compliance_fixes', 'venv.Lib.site-packages.keras_applications',
              'venv.Lib.site-packages.virtualenv_support', 'venv.Lib.site-packages.widgetsnbextension',
              'venv.Lib.site-packages.keras_preprocessing', 'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.idna',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pytoml',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.certifi',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet.cli',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib._backport',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.msgpack',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.util',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib._securetransport',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.backports',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.colorama',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treebuilders',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.lockfile',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.progress',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.requests',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.packaging',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.webencodings',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.req',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.vcs',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.utils',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.models',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.commands',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.operations'],
    url='',
    license='',
    author='Tiran',
    author_email='',
    description=''
)
